### PR TITLE
Try to use monad classes to avoid mtl complexity

### PR DESCRIPTION
**Pull request by qnikst**

### CODE REVIEW

**Comment by cblp** [comment]
Does it pass tests?

**Comment by cblp** [comment]
MonadCache is used for tests, why did you removed it?

**Comment by qnikst** [comment]
I suppose, I just missed that. I think MonadCache can be easily restored. 
In order to solve conflicts almost everything should rechecked. So I'm closing this PR.

**Comment by cblp** [comment]
I'd like to take some ideas from your code.

**Comment by qnikst** [comment]
I'm not removing branch, and is going to update it, so feel free to get code from https://github.com/qnikst/notifaika/tree/monad-classes it will not disappear :)

**Pull request closed without merging**
